# Generated by Django 6.0.2 on 2026-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('opening_hours', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('delivery', models.BooleanField()),
                ('rating', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Italian', 'Italian'), ('Sushi', 'Sushi'), ('Ushqime deti', 'Ushqime deti'), ('Tradicional', 'Tradicional'), ('Fast food', 'Fast food'), ('Pasticeri', 'Pasticeri'), ('Pica', 'Pica')])),
                ('logo_link', models.URLField(blank=True, default=None)),
                ('map_link', models.URLField(blank=True, default=None)),
                ('facebook_link', models.URLField(blank=True, default=None)),
                ('instagram_link', models.URLField(blank=True, default=None)),
                ('tiktok_link', models.URLField(blank=True, default=None)),
                ('web_link', models.URLField(blank=True, default=None)),
            ],
        ),
    ]
