# Generated by Django 6.0.2 on 2026-02-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Platinium', 'Platinium'), ('Gold', 'Gold')], default='Free'),
        ),
    ]
