# Generated by Django 6.0.2 on 2026-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_halal_menuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('Sallata', 'Sallata'), ('Antipasta', 'Antipasta'), ('Pasta', 'Pasta'), ('Rizoto', 'Rizoto'), ('Mish', 'Mish'), ('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Embelsira', 'Embelsira'), ('Hosomaki', 'Hosomaki'), ('Uramaki', 'Uramaki'), ('Uramaki-futomaki', 'Uramaki-futomaki'), ('Soups', 'Soups'), ('Drinks', 'Drinks'), ('Sides', 'Sides'), ('Kids', 'Kids'), ('Sanduich', 'Sanduich')], default='Mish'),
            preserve_default=False,
        ),
    ]
